---
- name: Run Django management commands with virtual environment activation
  hosts: webserver
  tasks:
    - name: Gathering Facts
      ansible.builtin.setup:

    - name: Activate virtual environment and run commands
      ansible.builtin.shell:
        cmd: |
          source /home/kali/Gametime/venv/bin/activate &&
          python manage.py collectstatic --no-input &&
          python manage.py check
        executable: /bin/bash
        chdir: /home/kali/Gametime

