version: '3'

services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - /Users/will/Gametime/app/nba_notifier/ssl:/etc/apache2/ssl  # Mount SSL files into Apache container
      - ./apache.conf:/etc/apache2/sites-available/apache.conf:ro   # Mount Apache configuration file

  apache:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    volumes:
      - /Users/will/Gametime/app/nba_notifier/ssl:/etc/apache2/ssl  # Mount SSL files into Apache container
      - ./apache.conf:/etc/apache2/sites-available/apache.conf:ro   # Mount Apache configuration file

