version: '3'

services:
  django:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - /Users/will/Gametime/app/nba_notifier/ssl:/etc/apache2/ssl  # Mount SSL files into Apache container
    env_file:
      - ssl.env
	
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "8443:8443"
    volumes:
      - /Users/will/Gametime/nginx.conf:/etc/nginx/nginx.conf:ro  # Mount Nginx configuration file
      - /Users/will/Gametime/app/nba_notifier/ssl:/etc/apache2/ssl  # Mount SSL files into Nginx container
    command: ["/usr/sbin/nginx", "-g", "daemon off;"]


