branch-defaults:
  default:
    environment: Gametime-env
  dev:
    environment: Github-Automation
environment-defaults:
  Gametime-env:
    branch: null
    repository: null
  game-monitor-dev2:
    branch: null
    repository: null
global:
  application_name: game_monitor
  default_ec2_keyname: null
  default_platform: Python 3.11 running on 64bit Amazon Linux 2023
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: null
  workspace_type: Application
