"""
Django settings for nba_notifier project.

Generated by 'django-admin startproject' using Django 5.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
from pathlib import Path
from celery.schedules import crontab
from dotenv import load_dotenv

BASE_DIR = Path(__file__).resolve().parent.parent.parent

# Load .env file from the base directory
load_dotenv(dotenv_path=BASE_DIR / '.env')
'''
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'level': 'WARNING',
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'WARNING',
            'propagate': True,
        },
    },
}
'''


# Use environment variables
SECRET_KEY = os.getenv("SECRET_KEY", "default-secret-key")

SSL_CERTIFICATE = os.environ.get('SSL_CERTIFICATE')
SSL_PRIVATE_KEY = os.environ.get('SSL_PRIVATE_KEY')

# Remove or comment out Twilio settings
# TWILIO_ACCOUNT_SID = os.getenv("TWILIO_ACCOUNT_SID", "default-sid")
# TWILIO_AUTH_TOKEN = os.getenv("TWILIO_AUTH_TOKEN", "default-token")
# TWILIO_PHONE_NUMBER = os.getenv("TWILIO_PHONE_NUMBER", "+18888354844")
# print("TWILIO_ACCOUNT_SID:", TWILIO_ACCOUNT_SID)
# print("TWILIO_AUTH_TOKEN:", TWILIO_AUTH_TOKEN)
# print("TWILIO_PHONE_NUMBER:", TWILIO_PHONE_NUMBER)

CELERY_RESULT_BACKEND = (
    "redis://localhost:6379/0"
)

CELERY_BEAT_SCHEDULE = {
    "start-daily-game-checks": {
        "task": "game_monitor.tasks.start_game_checks",
        "schedule": crontab(hour=0, minute=30),
        "args": (),
    },
    "frequent-game-score-checks": {
        "task": "game_monitor.tasks.frequent_game_score_checks",
        "schedule": crontab(minute="*/5"),
        "args": (),
    },
}

STATIC_ROOT = BASE_DIR / 'staticfiles'
STATIC_URL = '/static/'

DEBUG = False  # Set to False for deployment

ALLOWED_HOSTS = ['*']

SECURE_SSL_REDIRECT = False  # Enable SSL redirection
SECURE_HSTS_SECONDS = 31536000  # Enable HSTS with a one-year duration
SECURE_HSTS_INCLUDE_SUBDOMAINS = True  # Apply HSTS to all subdomains
SECURE_HSTS_PRELOAD = True  # Allow the site to be preloaded by browsers

SESSION_COOKIE_SECURE = True  # Ensure session cookies are only sent over HTTPS
CSRF_COOKIE_SECURE = True  # Ensure CSRF cookies are only sent over HTTPS

CORS_ORIGIN_WHITELIST = [
    'http://localhost:8000',  # Replace with your frontend URL
    'http://127.0.0.1:8000',   # Replace with your frontend URL
    # Add other origins as needed
]

INSTALLED_APPS = [
    "django.contrib.admin",
    "django_extensions",
    "django_prometheus",
    #'debug_toolbar',
    'sslserver',
    'corsheaders',
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "game_monitor.apps.GameMonitorConfig",
    "django_celery_beat",
    "nba_notifier",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    'corsheaders.middleware.CorsMiddleware',
    "django.middleware.common.CommonMiddleware",
    #'debug_toolbar.middleware.DebugToolbarMiddleware',
    'django_prometheus.middleware.PrometheusBeforeMiddleware',
    'django_prometheus.middleware.PrometheusAfterMiddleware',
    #"django.middleware.csrf.CsrfViewMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
]


CORS_ALLOWED_ORIGINS = [
    "http://localhost:8000",  # Replace with your frontend origin
    "http://127.0.0.1:8000",  # Replace with your frontend origin
]

CORS_ALLOW_CREDENTIALS = True

ROOT_URLCONF = "nba_notifier.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DIR, "game_monitor", "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "django.template.context_processors.csrf",
            ],
        },
    },
]

WSGI_APPLICATION = "nba_notifier.wsgi.application"

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

CELERY_BROKER_URL = "redis://localhost:6379/0"
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"

CSRF_TRUSTED_ORIGINS = [
    'http://localhost:8000',
    'http://localhost,',
    'https://localhost',
    'https://localhost:8000',
    'http://127.0.0.1:8000',
    'https://127.0.0.1:8000',
    'http://0.0.0.0:8089',
]

