global:
  scrape_interval: 10s
  evaluation_interval: 10s
rule_files:
  - rules.yml

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alert-manager:9093

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - prometheus:9090

  - job_name: node
    static_configs:
      - targets:
          - node-exporter:9100

  - job_name: 'django-app'
    static_configs:
      - targets: ['localhost:8000']

  - job_name: 'django-app-metrics'
    scrape_interval: 10s
    metrics_path: /metrics
    static_configs:
      - targets: ['localhost:8000']

  - job_name: 'locust'
    scrape_interval: 10s
    metrics_path: /
    static_configs:
      - targets: ['localhost:8000']  # Adjust target address if necessary

