apiVersion: v1
kind: Service
metadata:
  name: django-service
spec:
  selector:
    app: django-app
  ports:
    - protocol: TCP
      port: 80  # Port exposed by the service
      targetPort: 8000  # Port your Django app listens on
  type: ClusterIP  # Type of service

