apiVersion: v1
kind: Service
metadata:
  name: django-service
spec:
  selector:
    app: django-app
  ports:
    - protocol: TCP
      port: 80            # Port exposed by the service
      targetPort: 8000    # Port your Django app listens on
      nodePort: 31111     # Specify a NodePort to expose the service externally
  type: NodePort          # Type of service

