# Generated by Django 4.2.10 on 2024-02-19 16:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("game_monitor", "0003_game"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
