# Generated by Django 4.2.10 on 2024-02-20 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game_monitor', '0004_alter_game_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='away_team_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='home_team_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
